### ISSUE TITLE
Alter table drop constraint name complains the contraint does not exist

### ISSUE THREAD

**Issue by twhiteman** [dolthub/go-mysql-server#1632]
I get the following error:
`ERROR 1105 (HY000): Constraint "user_id_unique" does not exist`

This works against a regular mysql server, but not against GMS (with EnablePrimaryKeyIndexes enabled).

SQL:
```
CREATE TABLE `user`
(
    `user_id` VARCHAR(10) NOT NULL
);

ALTER TABLE `user` ADD CONSTRAINT `user_id_unique` UNIQUE (`user_id`);

ALTER TABLE `user` DROP CONSTRAINT `user_id_unique`;
```

I noticed the following differences when performing a `show create table`:
Mysql:
```
UNIQUE KEY `user_id_unique` (`user_id`)
```

GMS:
```
 UNIQUE KEY `user_id` (`user_id`)
```

**Comment by timsehn** [comment]
This is also not an issue in Dolt so it has something to do with the way GMS does in memory unique indexes.

**Comment by JCOR11599** [comment]
Hey @twhiteman, I believe this issue is related: https://github.com/dolthub/dolt/issues/5479
The problem was in our parser, which we fixed in this PR: https://github.com/dolthub/vitess/pull/225

So, I think the updated GMS should handle constraint names correctly now. Lemme know if this resolves your issue.

**Comment by twhiteman** [comment]
That was it - nice work! All working great now!
