### ISSUE TITLE
Error 1105: -128 out of range for BIGINT UNSIGNED

### ISSUE THREAD

**Issue by niclausse** [dolthub/go-mysql-server#1782]
INSERT INTO `tblOmsAccountInfo` (`id`, `uid`, `puid`, `identity`, `org_id`, `org_type`, `name`, `pinyin`, `status`, `create_uid`, `op_uid`, `created_at`, `updated_at`, `deleted_at`) VALUES (146, 3000028484, 3000028484, 1, 0, 0, '唐北山', 'tangbeishan', 0, 3000028484, 3000028484, '2023-02-20 15:47:01.206', '2023-02-20 15:47:01.206', NULL)";  

Execute  this SQL in version 0.11.0， return the 'out of range for BIGINT UNSIGNED' ERROR,  but version 0.15.0 works.  Can I solve it without updating version

**Comment by timsehn** [comment]
Unlikely. @fulghum ?

**Comment by fulghum** [comment]
Hey @niclausse, happy to investigate this. Can you help provide a simple repro for this? For example, can you provide the simplest create table` statement and an `insert` statement to repro the problem? I'll take a look later today and see what I can find, but whenever we can get an exact repro commands/code to run, we can always help faster.

**Comment by niclausse** [comment]
> 

Thanks for your reply,  the ERROR occurs when my inserting data grows. So it may be caused by memory usage?   Here is my demo codes: https://github.com/niclausse/lib-examples/blob/main/testdb/mysql_test.go

**Comment by fulghum** [comment]
Hey @niclausse, sorry for the delay. I was just going through the queue and noticed you have given us a nice repro code sample. I ran that this morning and I was able to generate the same error. I only see this happen with "BIGINT UNSIGNED" and I was able to simplify the insert statements needed to generate the error to just the two inserts: IDs `127` and `128`. 

I tried to run that same repro with the tip of go-mysql-server, but wasn't able to repro there yet. If you get a chance to update your repro sample to use the latest version of go-mysql-server, that would be another helpful datapoint. There's a chance it might work with the latest, since I couldn't repro, but it could also be something else in the test set up of course. 

I also tried to repro this with Dolt, just as another experiment. I couldn't repro with Dolt yet either.

**Comment by yx1215** [comment]
I met the same error, the following is a simple script that I can reproduce the error
```
package main

import (
	"database/sql"
	"fmt"
	sqle "github.com/dolthub/go-mysql-server"
	"github.com/dolthub/go-mysql-server/memory"
	"github.com/dolthub/go-mysql-server/server"
	_ "github.com/go-sql-driver/mysql"
	"time"
)

func main() {
	engine := sqle.NewDefault(memory.NewDBProvider())

	config := server.Config{
		Protocol: "tcp",
		Address:  fmt.Sprintf("localhost:3307"),
	}

	s, err := server.NewDefaultServer(config, engine)
	if err != nil {
		fmt.Println(err)
		return
	}

	go func() {
		if err := s.Start(); err != nil {
			return
		}
	}()

	conn, err := sql.Open("mysql", "no_user:@tcp(localhost:3307)/")
	_, _ = conn.Exec("CREATE DATABASE demo")
	_, _ = conn.Exec("CREATE TABLE demo.user_info (\n    id BIGINT PRIMARY KEY AUTO_INCREMENT,\n    aid BIGINT UNSIGNED\n)")
	_ = conn.Close()

	db, err := sql.Open("mysql", "no_user:@tcp(localhost:3307)/demo")

	_, err := db.Exec("INSERT INTO `user_info` (id, aid) VALUES (?, ?)", 0, uint64(9223372036854775808))
	if err != nil {
		fmt.Println(err)
                return
	}
}
```

Notice that 9223372036854775808 is (max int64) + 1.
The error won't appear for numbers smaller or equal to max int64. So I think somewhere inside the implementation uint64 is treated as int64?

**Comment by fulghum** [comment]
Closing this one, since we haven't heard anything back in several months. Feel free to reopen or cut us a new issue if you're still having problems and we'll be happy to help.
