### ISSUE TITLE
Potential regression: number cast to JSON no longer read as float

### ISSUE THREAD

**Issue by joheriks** [dolthub/go-mysql-server#2391]
Trying to get a decimal number cast to `JSON` into a go `float64`:

```go
rows, err := conn.Query("SELECT CAST(321.4 AS JSON)")
require.NoError(t, err)
for rows.Next() {
  var row float64
  rows.Scan(&row)
  fmt.Println("Row is", row)
}
```
with `github.com/dolthub/go-mysql-server@v0.17.0` prints:
```
Row is 321.4
```
However, with the `github.com/dolthub/go-mysql-server@v0.18.0` the value is discarded:
```
Row is 0
```

**Comment by nicktobey** [comment]
Hi Johannes!

`rows.Scan` returns an `error`, and insepcting this error reveals some additional context.

It looks like the issue here is that `SELECT CAST(321.4 AS JSON)` is incorrectly returning a JSON document containing the string "321.4", when it should be returning a JSON document containing a float or decimal value `321.4`. This violates the MySQL documentation [here](https://dev.mysql.com/doc/refman/8.0/en/json.html#json-converting-between-types)

I'm working on a fix now.

**Comment by joheriks** [comment]
Thank you for the quick response and fix @nicktobey
