### ISSUE TITLE
`go get github.com/dolthub/go-mysql-server` got the wrong path?

### ISSUE THREAD

**Issue by JasonkayZK** [dolthub/go-mysql-server#281]
I tried to import the dependency using `go get github.com/dolthub/go-mysql-server`, but i got err msg:

```bash
$ go get github.com/dolthub/go-mysql-server
go: github.com/dolthub/go-mysql-server upgrade => v0.6.0
go get: github.com/dolthub/go-mysql-server@v0.6.0: parsing go.mod:
        module declares its path as: github.com/liquidata-inc/go-mysql-server
                but was required as: github.com/dolthub/go-mysql-server
```

If you use `go mod tidy` to import the dependencies in the example, you can also encounter this problem!

So, i'm wondering if you can solve this problem?

**Comment by zachmu** [comment]
Think the problem is that the most recent release had tag '0.7.0' instead of 'v0.7.0', so it went for v0.6.0 instead.

In any case I've now release v0.8.0 off master but, I'm not sure it's working right. I see:

```
go get github.com/dolthub/go-mysql-server
# github.com/dolthub/go-mysql-server/sql/expression/function/aggregation
C:\Users\Zach Musgrave\go\src\github.com\dolthub\go-mysql-server\sql\expression\function\aggregation\count.go:165:33: no
t enough arguments in call to hashstructure.Hash
        have (interface {}, nil)
        want (interface {}, hashstructure.Format, *hashstructure.HashOptions)
```

It probably depends what version of github.com/mitchellh/hashstructure you have installed. The project uses 1.0.0.

**Comment by JasonkayZK** [comment]
The v0.8.0 works fine with me. Thx!!! ♥
