### ISSUE TITLE
sql.FilteredTable usage and implementation

### ISSUE THREAD

**Issue by nemccarthy** [dolthub/go-mysql-server#399]
I've just started looking at go-mysql-server and it seems very powerful - for a particular use case I have in mind I'm looking at using a data source where I would like to implement the `sql.FilteredTable` when querying data (since the underlying API for this data source can filter the data more efficiently).

However from the documentation/code, its not clear what action the `HandledFilters` & `WithFilters` should perform. 

```
// FilteredTable is a table that can produce a specific RowIter
// that's more optimized given the filters.
type FilteredTable interface {
	Table
	HandledFilters(filters []Expression) []Expression
	WithFilters(filters []Expression) Table
}
```

Further the `memory` ref implementation seems to indicate that filter pushdowns are "broken" - is this in reference to the query engine being able to support them or just the memory implementation. 

```
	// pushdown info
	filters    []sql.Expression // currently unused, filter pushdown is significantly broken right now
	projection []string
	columns    []int
```
and

```
// sql.FilteredTable functionality in the Table type was disabled for a long period of time, and has developed major
// issues with the current analyzer logic. It's only used in the pushdown unit tests, and sql.FilteredTable should be
// considered unstable until this situation is fixed.
type FilteredTable struct {
	*Table
}
```

**Comment by zachmu** [comment]
Hi @nemccarthy,

Sorry for the long response time!

Filtered table does work, but it's less well tested than other parts of the engine, as the comment you found indicates. It does work, we just have less confidence in it. Dolt implements this interface for some of its tables:

github.com/dolthub/dolt

That said, it's very possible that there are bugs in its operation that we haven't found, because the tests are less complete. The in-memory implementation is pretty broken right now.

If you want to implement it yourself, feel free! Just be aware that pre-1.0, the interfaces may change and break you.

HandledFilters returns which of the Expressions given can be handled by the table, and WithFilters requests a version of the table  with those filters applied. Check out the only use of this interface in pushdown.go for an idea of how it's supposed to work.

Hope that helps!
